### ISSUE TITLE
Plugin window not selecting correct setting and title

### ISSUE THREAD

**Issue by diegopradogesto** [Ghostkeeper/SettingsGuide#1]
**Description:** When open the plugin through right click on a setting, the window opens but it doesn't show any information.
Funny thing though is that if you select a setting in the plugin, then close the dialog, then right click on a different setting and open the plugin again, the selected setting is still incorrect, the title is also incorrect **but** the description is actually the one from the setting that I want to look at.

**Version:** 1.2.0

**Operating System:** macOS

**Reproduce steps:**
1. Open Cura (with the plugin installed)
2. Open print settings panel
3. Right click on "Layer Height". Select Setting Guide

**Actual result:** The dialog appears but not information about the selected setting.

**Expected result:** The dialog shows information about "Layer Height".

**Reproducibility:** 100%

**Comment by Ghostkeeper** [comment]
Indeed I didn't even know that was a feature. I can take a look next weekend.
