### ISSUE TITLE
Background for side-menu content is transparent

### ISSUE THREAD

**Issue by shimoni-shaked** [Ghostkeeper/SettingsGuide#104]
After installing the plugin the background for the side-menu content is transparent. The plugin itself works. Cura 5.0.0, installed your latest version from the marketplace.
I used the default dark theme modified with a bigger font size, but changing to the default light theme hadn't fixed it either.
[theme.txt](https://github.com/Ghostkeeper/SettingsGuide/files/9482736/theme.txt)
![image](https://user-images.githubusercontent.com/51531847/188274170-16eb837f-2ad5-417c-a9f5-fbcfa7047bc0.png)
![image](https://user-images.githubusercontent.com/51531847/188274439-d3b7429b-43fa-425d-b666-da087bc650ec.png)

**Comment by Ghostkeeper** [comment]
Yeah, I've seen this as well. It's got something to do with the Settings Guide adjusting the width of that tooltip, which is the same re-useable component (`PointingRectangle`) as what is used for the background of the tool panels since 5.0. I'll see what I can do.
