### ISSUE TITLE
In some help points the choice of translation into Russian disappears.

### ISSUE THREAD

**Issue by airjt-hub** [Ghostkeeper/SettingsGuide#128]
Cura  version 5.9.0

Settings Guide
2.9.2 - last update on 06-11-2022

In some help points the choice of translation into Russian disappears.
For example:
Top Surface Skin Layers: there is a choice of translation into Russian,
Top Surface Skin Line Width: there is no choice of translation into Russian

How to fix it?
Thank you.

**Comment by Ghostkeeper** [comment]
Not all articles had been translated into Russian. A Russian translation is only available for articles that were.

This is expected.
