### ISSUE TITLE
[Feature Request] Possibility to add  dependance parameter in the regular windows

### ISSUE THREAD

**Issue by 5axes** [Ghostkeeper/SettingsGuide#18]
Is it possible to have also in the regular Windows of the SettingsGuide the  dependance parameter as we have in the tooltip.
![request](https://user-images.githubusercontent.com/11015345/76948175-0652d200-6907-11ea-913f-97aed96da7c4.jpg)

**Comment by Ghostkeeper** [comment]
These dependencies can be different from printer to printer, so I'd rather not include that in the Settings Guide.

**Comment by 5axes** [comment]
it's not automaticaly generated ?

**Comment by Ghostkeeper** [comment]
It is. It's generated by looking at the formulas in the [printer definition](https://github.com/Ultimaker/Cura/blob/master/resources/definitions/ultimaker3.def.json). But it switches every time you switch printers. That's not really expected of a reference like the Settings Guide.
