### ISSUE TITLE
support/support_infill_angle.md

### ISSUE THREAD

**Issue by 5axes** [Ghostkeeper/SettingsGuide#23]
the same parameter is define two times in Articles
support/support_infill_angle.md
&
support/support_infill_angle**s**.md

![Support](https://user-images.githubusercontent.com/11015345/83661232-1b660580-a5c6-11ea-9ea2-411239a65630.JPG)

**Comment by Ghostkeeper** [comment]
That's correct. This is because the setting was changed in Cura 4.3 to allow specifying multiple angles that alternate between the layers.
