### ISSUE TITLE
2.7.0 Installation failed

### ISSUE THREAD

**Issue by 5axes** [Ghostkeeper/SettingsGuide#56]
Drag and Drop of the Cura package for installation doesn't install correctly the new version in Cura.

Tested on Win10 with Cura 4.9  and 4.10   with the SettingsGuide2.7.0-sdk7.0.0.curapackage  file.

hereafter the error message in cura after the restart 

![image](https://user-images.githubusercontent.com/11015345/123602016-9e24b880-d7f8-11eb-8523-dfcb27285f73.png)

**Comment by Ghostkeeper** [comment]
It's a bit weird, because the plug-in ID for the Settings Guide is `SettingsGuide2`, not `SettingsGuide`. Maybe something is colliding with a version of the SettingsGuide you installed from source?

**Comment by 5axes** [comment]
Ok yes it was an issue comming from a previous manual installation. 
Thank you for directing me to the solution
