### ISSUE TITLE
Documentation (popup help) missing critical info (unresolved ambiguity over "Initial Layer Height" - is this a setting or a nozzle-bed measurement?)

### ISSUE THREAD

**Issue by gitcnd** [Ghostkeeper/SettingsGuide#70]
See https://github.com/Ultimaker/Cura/issues/10893

**Comment by 5axes** [comment]
or https://github.com/Ultimaker/Cura/issues/9126

**Comment by Ghostkeeper** [comment]
Seems like something that could be added to the build plate adhesion troubleshooting article. Or perhaps to the Initial Layer Height article. I'll look into it.

**Comment by Ghostkeeper** [comment]
This is implemented in 54a9ae98b78b6b4a79c287a0a3185661709b7279. Thanks for the suggestion!
