### ISSUE TITLE
Add numerical interpretation of "Walls->Hole Horizontal Expansion"

### ISSUE THREAD

**Issue by avogra** [Ghostkeeper/SettingsGuide#76]
Hello,
I regularly stumble over "Walls->Hole Horizontal Expansion". I think, the implementation in Cura is non-intuitive. It would be great, if the guide would include, how exactly the number affects holes. The guide already explains that positive numbers make holes bigger but not by how much. Intuitively, i would expect that the diameter is increased by the entered value, but instead it seems to work similar to "Horizontal Expansion", where the value indicates the displacement of the walls. So if you enter a setting of 1mm the hole diameter will increase by 2mm. Maybe someone could confirm that? If I'm right, I would suggest to add the following to the guide:

The entered value indicates the displacement of the walls. So a value of 1mm will increase hole diameters by 2mm.

**Comment by Ghostkeeper** [comment]
Indeed, the value is the displacement of the contour, which then causes the displacement of the walls by the same amount. You got that right.

It's indeed something that could use clarifying. I'll add it to the article (in less technical words than here). Good suggestion!
