### ISSUE TITLE
Settings dialog obstructs Cura Machine Settings Inputs.

### ISSUE THREAD

**Issue by opensourcefan** [Ghostkeeper/SettingsGuide#95]
2.9.0 on Cura 5.0.0 as well as Cura 5.1.0

Preferences/Configure Cura.../Printers/Machine Settings - Hover over inputs especially Start and End G-code, Settings dialog completely blocks input fields. This forces you to quickly enter the desired value prior to the Settings dialog opening.

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ghostkeeper/SettingsGuide/issues/89
